# Generated by Django 3.2.5 on 2024-01-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231027_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accuracy_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='test_times',
            field=models.IntegerField(default=0),
        ),
    ]
